### PR TITLE
Fix 8579

### PR DESCRIPTION
**Pull request by TheAwiteb**
Fix of unplanned feature, for my personal use

https://github.com/helix-editor/helix/issues/8579

### CODE REVIEW

**Comment by brokenthorn** [comment]
Would you mind merging this into the main helix repo?

**Comment by TheAwiteb** [comment]
> Would you mind merging this into the main helix repo?

Of course not, there is already a PR work in a solution for this issue https://github.com/helix-editor/helix/pull/3958

**Comment by TheAwiteb** [comment]
The [dev](https://github.com/TheAwiteb/helix/tree/dev) branch will be always rebased with the helix master branch, you can install Helix from this branch by [`--branch`](https://doc.rust-lang.org/cargo/commands/cargo-install.html#install-options) until the feature comes to Helix

**Comment by TheAwiteb** [comment]
You can know how it's work by this [config file](https://gist.github.com/TheAwiteb/8077cbf866e8613d7f07fcfa0aa9ea63)

**Pull request merged**
